// <auto-generated />
using HostDeck.Infrastructure.Persistence;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace HostDeck.Infrastructure.Persistence.Migrations
{
    [DbContext(typeof(HostDeckDbContext))]
    [Migration("20260907223443_AddServerSystemIdentity")]
    partial class AddServerSystemIdentity
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder.HasAnnotation("ProductVersion", "10.0.11");

            modelBuilder.Entity("HostDeck.Infrastructure.Persistence.Records.AlertRuleRecord", b =>
                {
                    b.Property<string>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TEXT");

                    b.Property<int?>("ComparisonOperator")
                        .HasColumnType("INTEGER");

                    b.Property<int>("CooldownSeconds")
                        .HasColumnType("INTEGER");

                    b.Property<long>("CreatedAt")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Description")
                        .HasMaxLength(512)
                        .HasColumnType("TEXT");

                    b.Property<int>("DurationSeconds")
                        .HasColumnType("INTEGER");

                    b.Property<bool>("IsEnabled")
                        .HasColumnType("INTEGER");

                    b.Property<int>("Metric")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(128)
                        .HasColumnType("TEXT");

                    b.Property<string>("ScopeGroup")
                        .HasMaxLength(64)
                        .HasColumnType("TEXT");

                    b.Property<int>("ScopeKind")
                        .HasColumnType("INTEGER");

                    b.Property<string>("ScopeServerId")
                        .HasColumnType("TEXT");

                    b.Property<int>("Severity")
                        .HasColumnType("INTEGER");

                    b.Property<double?>("ThresholdValue")
                        .HasColumnType("REAL");

                    b.Property<long>("UpdatedAt")
                        .HasColumnType("INTEGER");

                    b.HasKey("Id");

                    b.HasIndex("IsEnabled")
                        .HasDatabaseName("ix_alert_rules_enabled");

                    b.ToTable("alert_rules", (string)null);
                });

            modelBuilder.Entity("HostDeck.Infrastructure.Persistence.Records.DiskMetricSampleRecord", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("FileSystem")
                        .HasMaxLength(256)
                        .HasColumnType("TEXT");

                    b.Property<string>("MountPoint")
                        .IsRequired()
                        .HasMaxLength(4096)
                        .HasColumnType("TEXT");

                    b.Property<long>("ObservedAt")
                        .HasColumnType("INTEGER");

                    b.Property<string>("ServerId")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<long>("TotalBytes")
                        .HasColumnType("INTEGER");

                    b.Property<long>("UsedBytes")
                        .HasColumnType("INTEGER");

                    b.HasKey("Id");

                    b.HasIndex("ObservedAt")
                        .HasDatabaseName("ix_disk_metric_samples_time");

                    b.HasIndex("ServerId", "ObservedAt")
                        .HasDatabaseName("ix_disk_metric_samples_server_time");

                    b.ToTable("disk_metric_samples", (string)null);
                });

            modelBuilder.Entity("HostDeck.Infrastructure.Persistence.Records.DockerContainerRecord", b =>
                {
                    b.Property<string>("ContainerId")
                        .HasMaxLength(64)
                        .HasColumnType("TEXT");

                    b.Property<int>("Health")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Image")
                        .IsRequired()
                        .HasMaxLength(512)
                        .HasColumnType("TEXT");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("TEXT");

                    b.Property<long>("ObservedAt")
                        .HasColumnType("INTEGER");

                    b.Property<int>("RestartCount")
                        .HasColumnType("INTEGER");

                    b.Property<string>("ServerId")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<long?>("StartedAt")
                        .HasColumnType("INTEGER");

                    b.Property<int>("Status")
                        .HasColumnType("INTEGER");

                    b.HasKey("ContainerId");

                    b.HasIndex("ServerId")
                        .HasDatabaseName("ix_docker_containers_server");

                    b.ToTable("docker_containers", (string)null);
                });

            modelBuilder.Entity("HostDeck.Infrastructure.Persistence.Records.DockerHostRecord", b =>
                {
                    b.Property<string>("ServerId")
                        .HasColumnType("TEXT");

                    b.Property<string>("EngineVersion")
                        .IsRequired()
                        .HasMaxLength(64)
                        .HasColumnType("TEXT");

                    b.Property<int>("Images")
                        .HasColumnType("INTEGER");

                    b.Property<long>("ObservedAt")
                        .HasColumnType("INTEGER");

                    b.Property<int>("RunningContainers")
                        .HasColumnType("INTEGER");

                    b.Property<int>("TotalContainers")
                        .HasColumnType("INTEGER");

                    b.HasKey("ServerId");

                    b.ToTable("docker_hosts", (string)null);
                });

            modelBuilder.Entity("HostDeck.Infrastructure.Persistence.Records.DockerMetricSampleRecord", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<long>("BlockReadBytes")
                        .HasColumnType("INTEGER");

                    b.Property<long>("BlockWrittenBytes")
                        .HasColumnType("INTEGER");

                    b.Property<string>("ContainerId")
                        .IsRequired()
                        .HasMaxLength(64)
                        .HasColumnType("TEXT");

                    b.Property<double>("CpuPercent")
                        .HasColumnType("REAL");

                    b.Property<long>("MemoryLimitBytes")
                        .HasColumnType("INTEGER");

                    b.Property<long>("MemoryUsedBytes")
                        .HasColumnType("INTEGER");

                    b.Property<long>("NetworkReceivedBytes")
                        .HasColumnType("INTEGER");

                    b.Property<long>("NetworkTransmittedBytes")
                        .HasColumnType("INTEGER");

                    b.Property<long>("ObservedAt")
                        .HasColumnType("INTEGER");

                    b.Property<string>("ServerId")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("ObservedAt")
                        .HasDatabaseName("ix_docker_metric_samples_time");

                    b.HasIndex("ContainerId", "ObservedAt")
                        .HasDatabaseName("ix_docker_metric_samples_container_time");

                    b.ToTable("docker_metric_samples", (string)null);
                });

            modelBuilder.Entity("HostDeck.Infrastructure.Persistence.Records.IncidentEventRecord", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("Actor")
                        .HasMaxLength(128)
                        .HasColumnType("TEXT");

                    b.Property<string>("Detail")
                        .HasMaxLength(1024)
                        .HasColumnType("TEXT");

                    b.Property<string>("IncidentId")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<int>("Kind")
                        .HasColumnType("INTEGER");

                    b.Property<long>("OccurredAt")
                        .HasColumnType("INTEGER");

                    b.HasKey("Id");

                    b.HasIndex("IncidentId", "OccurredAt")
                        .HasDatabaseName("ix_incident_events_incident_time");

                    b.ToTable("incident_events", (string)null);
                });

            modelBuilder.Entity("HostDeck.Infrastructure.Persistence.Records.IncidentRecord", b =>
                {
                    b.Property<string>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TEXT");

                    b.Property<long?>("AcknowledgedAt")
                        .HasColumnType("INTEGER");

                    b.Property<string>("AcknowledgedBy")
                        .HasMaxLength(128)
                        .HasColumnType("TEXT");

                    b.Property<double?>("CurrentValue")
                        .HasColumnType("REAL");

                    b.Property<long?>("LastNotifiedAt")
                        .HasColumnType("INTEGER");

                    b.Property<long>("LastUpdatedAt")
                        .HasColumnType("INTEGER");

                    b.Property<int>("Metric")
                        .HasColumnType("INTEGER");

                    b.Property<long?>("RecoveredAt")
                        .HasColumnType("INTEGER");

                    b.Property<long?>("ResolvedAt")
                        .HasColumnType("INTEGER");

                    b.Property<string>("RuleId")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("ServerId")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<int>("Severity")
                        .HasColumnType("INTEGER");

                    b.Property<long>("StartedAt")
                        .HasColumnType("INTEGER");

                    b.Property<int>("Status")
                        .HasColumnType("INTEGER");

                    b.Property<double?>("ThresholdValue")
                        .HasColumnType("REAL");

                    b.HasKey("Id");

                    b.HasIndex("StartedAt")
                        .HasDatabaseName("ix_incidents_started_at");

                    b.HasIndex("Status")
                        .HasDatabaseName("ix_incidents_status");

                    b.HasIndex("ServerId", "RuleId", "Status")
                        .HasDatabaseName("ix_incidents_server_rule_status");

                    b.ToTable("incidents", (string)null);
                });

            modelBuilder.Entity("HostDeck.Infrastructure.Persistence.Records.MetricSampleRecord", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<int>("CoreCount")
                        .HasColumnType("INTEGER");

                    b.Property<double>("CpuIoWait")
                        .HasColumnType("REAL");

                    b.Property<double>("CpuNice")
                        .HasColumnType("REAL");

                    b.Property<double>("CpuSteal")
                        .HasColumnType("REAL");

                    b.Property<double>("CpuSystem")
                        .HasColumnType("REAL");

                    b.Property<double>("CpuUser")
                        .HasColumnType("REAL");

                    b.Property<double>("LoadFifteen")
                        .HasColumnType("REAL");

                    b.Property<double>("LoadFive")
                        .HasColumnType("REAL");

                    b.Property<double>("LoadOne")
                        .HasColumnType("REAL");

                    b.Property<long>("MemoryBuffersBytes")
                        .HasColumnType("INTEGER");

                    b.Property<long>("MemoryCachedBytes")
                        .HasColumnType("INTEGER");

                    b.Property<long>("MemoryTotalBytes")
                        .HasColumnType("INTEGER");

                    b.Property<long>("MemoryUsedBytes")
                        .HasColumnType("INTEGER");

                    b.Property<long>("ObservedAt")
                        .HasColumnType("INTEGER");

                    b.Property<string>("ServerId")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<long>("SwapTotalBytes")
                        .HasColumnType("INTEGER");

                    b.Property<long>("SwapUsedBytes")
                        .HasColumnType("INTEGER");

                    b.Property<double>("UptimeSeconds")
                        .HasColumnType("REAL");

                    b.HasKey("Id");

                    b.HasIndex("ObservedAt")
                        .HasDatabaseName("ix_metric_samples_time");

                    b.HasIndex("ServerId", "ObservedAt")
                        .HasDatabaseName("ix_metric_samples_server_time");

                    b.ToTable("metric_samples", (string)null);
                });

            modelBuilder.Entity("HostDeck.Infrastructure.Persistence.Records.NetworkMetricSampleRecord", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("InterfaceName")
                        .IsRequired()
                        .HasMaxLength(64)
                        .HasColumnType("TEXT");

                    b.Property<long>("ObservedAt")
                        .HasColumnType("INTEGER");

                    b.Property<long>("ReceivedBytes")
                        .HasColumnType("INTEGER");

                    b.Property<string>("ServerId")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<long>("TransmittedBytes")
                        .HasColumnType("INTEGER");

                    b.HasKey("Id");

                    b.HasIndex("ObservedAt")
                        .HasDatabaseName("ix_network_metric_samples_time");

                    b.HasIndex("ServerId", "ObservedAt")
                        .HasDatabaseName("ix_network_metric_samples_server_time");

                    b.ToTable("network_metric_samples", (string)null);
                });

            modelBuilder.Entity("HostDeck.Infrastructure.Persistence.Records.ServerRecord", b =>
                {
                    b.Property<string>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TEXT");

                    b.Property<string>("Address")
                        .IsRequired()
                        .HasMaxLength(253)
                        .HasColumnType("TEXT");

                    b.Property<long>("CreatedAt")
                        .HasColumnType("INTEGER");

                    b.Property<string>("CredentialKey")
                        .IsRequired()
                        .HasMaxLength(128)
                        .HasColumnType("TEXT");

                    b.Property<int>("CredentialKind")
                        .HasColumnType("INTEGER");

                    b.Property<bool>("DockerEnabled")
                        .HasColumnType("INTEGER");

                    b.Property<string>("GroupName")
                        .HasMaxLength(64)
                        .HasColumnType("TEXT");

                    b.Property<string>("Hostname")
                        .HasMaxLength(256)
                        .HasColumnType("TEXT");

                    b.Property<string>("JumpHostAddress")
                        .HasMaxLength(253)
                        .HasColumnType("TEXT");

                    b.Property<string>("JumpHostCredentialKey")
                        .HasMaxLength(128)
                        .HasColumnType("TEXT");

                    b.Property<int?>("JumpHostCredentialKind")
                        .HasColumnType("INTEGER");

                    b.Property<int?>("JumpHostPort")
                        .HasColumnType("INTEGER");

                    b.Property<string>("JumpHostUsername")
                        .HasMaxLength(32)
                        .HasColumnType("TEXT");

                    b.Property<string>("KernelVersion")
                        .HasMaxLength(256)
                        .HasColumnType("TEXT");

                    b.Property<long?>("LastCollectedAt")
                        .HasColumnType("INTEGER");

                    b.Property<int>("MonitoringIntervalSeconds")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(128)
                        .HasColumnType("TEXT");

                    b.Property<string>("OperatingSystem")
                        .HasMaxLength(256)
                        .HasColumnType("TEXT");

                    b.Property<int>("Port")
                        .HasColumnType("INTEGER");

                    b.Property<int>("Status")
                        .HasColumnType("INTEGER");

                    b.Property<long>("UpdatedAt")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Username")
                        .IsRequired()
                        .HasMaxLength(32)
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("GroupName")
                        .HasDatabaseName("ix_servers_group");

                    b.HasIndex("Status")
                        .HasDatabaseName("ix_servers_status");

                    b.HasIndex("Address", "Port")
                        .IsUnique()
                        .HasDatabaseName("ix_servers_endpoint");

                    b.ToTable("servers", (string)null);
                });

            modelBuilder.Entity("HostDeck.Infrastructure.Persistence.Records.ServerTagRecord", b =>
                {
                    b.Property<string>("ServerId")
                        .HasColumnType("TEXT");

                    b.Property<string>("Tag")
                        .HasMaxLength(32)
                        .HasColumnType("TEXT");

                    b.HasKey("ServerId", "Tag");

                    b.HasIndex("Tag")
                        .HasDatabaseName("ix_server_tags_tag");

                    b.ToTable("server_tags", (string)null);
                });

            modelBuilder.Entity("HostDeck.Infrastructure.Persistence.Records.SettingsRecord", b =>
                {
                    b.Property<int>("Id")
                        .HasColumnType("INTEGER");

                    b.Property<bool>("AutoRefreshEnabled")
                        .HasColumnType("INTEGER");

                    b.Property<int>("AutoRefreshIntervalSeconds")
                        .HasColumnType("INTEGER");

                    b.Property<int>("CollectionRetryCount")
                        .HasColumnType("INTEGER");

                    b.Property<int>("CollectionTimeoutSeconds")
                        .HasColumnType("INTEGER");

                    b.Property<int>("DefaultCollectionIntervalSeconds")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Description")
                        .HasMaxLength(200)
                        .HasColumnType("TEXT");

                    b.Property<bool>("DesktopNotificationsEnabled")
                        .HasColumnType("INTEGER");

                    b.Property<int>("EventRetentionDays")
                        .HasColumnType("INTEGER");

                    b.Property<string>("InstanceName")
                        .IsRequired()
                        .HasMaxLength(64)
                        .HasColumnType("TEXT");

                    b.Property<int>("MaxConcurrentCollections")
                        .HasColumnType("INTEGER");

                    b.Property<int>("MetricRetentionDays")
                        .HasColumnType("INTEGER");

                    b.Property<int>("MinimumNotificationSeverity")
                        .HasColumnType("INTEGER");

                    b.Property<string>("StorageDirectory")
                        .HasMaxLength(4096)
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.ToTable("settings", null, t =>
                        {
                            t.HasCheckConstraint("ck_settings_single_row", "Id = 1");
                        });
                });

            modelBuilder.Entity("HostDeck.Infrastructure.Persistence.Records.SshHostKeyRecord", b =>
                {
                    b.Property<string>("Host")
                        .HasMaxLength(253)
                        .HasColumnType("TEXT");

                    b.Property<int>("Port")
                        .HasColumnType("INTEGER");

                    b.Property<long>("ApprovedAt")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Fingerprint")
                        .IsRequired()
                        .HasMaxLength(256)
                        .HasColumnType("TEXT");

                    b.HasKey("Host", "Port");

                    b.ToTable("ssh_host_keys", (string)null);
                });

            modelBuilder.Entity("HostDeck.Infrastructure.Persistence.Records.DiskMetricSampleRecord", b =>
                {
                    b.HasOne("HostDeck.Infrastructure.Persistence.Records.ServerRecord", null)
                        .WithMany()
                        .HasForeignKey("ServerId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("HostDeck.Infrastructure.Persistence.Records.DockerContainerRecord", b =>
                {
                    b.HasOne("HostDeck.Infrastructure.Persistence.Records.ServerRecord", null)
                        .WithMany()
                        .HasForeignKey("ServerId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("HostDeck.Infrastructure.Persistence.Records.DockerHostRecord", b =>
                {
                    b.HasOne("HostDeck.Infrastructure.Persistence.Records.ServerRecord", null)
                        .WithMany()
                        .HasForeignKey("ServerId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("HostDeck.Infrastructure.Persistence.Records.IncidentEventRecord", b =>
                {
                    b.HasOne("HostDeck.Infrastructure.Persistence.Records.IncidentRecord", null)
                        .WithMany()
                        .HasForeignKey("IncidentId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("HostDeck.Infrastructure.Persistence.Records.IncidentRecord", b =>
                {
                    b.HasOne("HostDeck.Infrastructure.Persistence.Records.ServerRecord", null)
                        .WithMany()
                        .HasForeignKey("ServerId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("HostDeck.Infrastructure.Persistence.Records.MetricSampleRecord", b =>
                {
                    b.HasOne("HostDeck.Infrastructure.Persistence.Records.ServerRecord", null)
                        .WithMany()
                        .HasForeignKey("ServerId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("HostDeck.Infrastructure.Persistence.Records.NetworkMetricSampleRecord", b =>
                {
                    b.HasOne("HostDeck.Infrastructure.Persistence.Records.ServerRecord", null)
                        .WithMany()
                        .HasForeignKey("ServerId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("HostDeck.Infrastructure.Persistence.Records.ServerTagRecord", b =>
                {
                    b.HasOne("HostDeck.Infrastructure.Persistence.Records.ServerRecord", null)
                        .WithMany("Tags")
                        .HasForeignKey("ServerId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("HostDeck.Infrastructure.Persistence.Records.ServerRecord", b =>
                {
                    b.Navigation("Tags");
                });
#pragma warning restore 612, 618
        }
    }
}
