<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <RootNamespace>HostDeck.Presentation.Tests</RootNamespace>
    <AvaloniaUseCompiledBindingsByDefault>true</AvaloniaUseCompiledBindingsByDefault>
  </PropertyGroup>

  <ItemGroup>
    <ProjectReference Include="..\..\src\HostDeck.Presentation\HostDeck.Presentation.csproj" />
  </ItemGroup>

  <ItemGroup>
    <PackageReference Include="Avalonia.Headless" />
    <PackageReference Include="Avalonia.Headless.XUnit" />
  </ItemGroup>

</Project>
